// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	io "io"

	sdk "github.com/api-freaks/sdk"
	core "github.com/api-freaks/sdk/core"
	internal "github.com/api-freaks/sdk/internal"
	option "github.com/api-freaks/sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Get detailed geolocation data for an IP address including country, city, timezone, currency, and optional security and user-agent information
func (c *Client) GeolocationLookup(
	ctx context.Context,
	request *sdk.GeolocationLookupRequest,
	opts ...option.RequestOption,
) (*sdk.GeolocationLookupResponse, error) {
	response, err := c.WithRawResponse.GeolocationLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve detailed geolocation data for multiple IP addresses in a single request.
// Supports up to `50,000` IP-addresses/host-names per request.
func (c *Client) BulkGeolocationLookup(
	ctx context.Context,
	request *sdk.BulkGeolocationLookupRequest,
	opts ...option.RequestOption,
) ([]*sdk.BulkGeolocationLookupResponseItem, error) {
	response, err := c.WithRawResponse.BulkGeolocationLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get comprehensive security information for a given IP address. Detects VPNs, proxies, Tor nodes, and other security threats.
func (c *Client) IPSecurityLookup(
	ctx context.Context,
	request *sdk.IPSecurityLookupRequest,
	opts ...option.RequestOption,
) (*sdk.IPSecurityLookupResponse, error) {
	response, err := c.WithRawResponse.IPSecurityLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The Bulk IP Security Lookup API allows you to retrieve security details for up to `50,000` IP-addresses in a single request.
func (c *Client) BulkIPSecurityLookup(
	ctx context.Context,
	request *sdk.BulkIPSecurityLookupRequest,
	opts ...option.RequestOption,
) ([]*sdk.BulkIPSecurityLookupResponseItem, error) {
	response, err := c.WithRawResponse.BulkIPSecurityLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Convert a given address or place name into geographic coordinates (latitude and longitude).
func (c *Client) GeocoderSearch(
	ctx context.Context,
	request *sdk.GeocoderSearchRequest,
	opts ...option.RequestOption,
) ([]*sdk.GeocoderSearchResponseItem, error) {
	response, err := c.WithRawResponse.GeocoderSearch(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Convert geographic coordinates (latitude and longitude) into a human-readable address or place name.
func (c *Client) GeocoderReverse(
	ctx context.Context,
	request *sdk.GeocoderReverseRequest,
	opts ...option.RequestOption,
) (*sdk.GeocoderReverseResponse, error) {
	response, err := c.WithRawResponse.GeocoderReverse(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve current WHOIS information for a domain name.
// This endpoint provides detailed registration information including registrar details,
// dates, nameservers, and registrant information.
func (c *Client) DomainWhoisLookup(
	ctx context.Context,
	request *sdk.DomainWhoisLookupRequest,
	opts ...option.RequestOption,
) (*sdk.DomainWhoisLookupResponse, error) {
	response, err := c.WithRawResponse.DomainWhoisLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve WHOIS information for `100 Domains per Request`.
func (c *Client) BulkDomainWhoisLookup(
	ctx context.Context,
	request *sdk.BulkDomainWhoisLookupRequest,
	opts ...option.RequestOption,
) (*sdk.BulkDomainWhoisLookupResponse, error) {
	response, err := c.WithRawResponse.BulkDomainWhoisLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns WHOIS registration details for a specified IP address (IPv4 or IPv6).
func (c *Client) IPWhoisLookup(
	ctx context.Context,
	request *sdk.IPWhoisLookupRequest,
	opts ...option.RequestOption,
) (*sdk.IPWhoisLookupResponse, error) {
	response, err := c.WithRawResponse.IPWhoisLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns WHOIS registration details for a specified ASN, with or without the 'as' prefix.
func (c *Client) AsnWhoisLookup(
	ctx context.Context,
	request *sdk.AsnWhoisLookupRequest,
	opts ...option.RequestOption,
) (*sdk.AsnWhoisLookupResponse, error) {
	response, err := c.WithRawResponse.AsnWhoisLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve historical WHOIS records for a domain name.
// This endpoint provides a timeline of all recorded changes in domain registration information.
func (c *Client) DomainWhoisHistory(
	ctx context.Context,
	request *sdk.DomainWhoisHistoryRequest,
	opts ...option.RequestOption,
) (*sdk.DomainWhoisHistoryResponse, error) {
	response, err := c.WithRawResponse.DomainWhoisHistory(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Performs a reverse WHOIS search using one or more search parameters like keyword, email, owner, or company.
func (c *Client) DomainWhoisReverse(
	ctx context.Context,
	request *sdk.DomainWhoisReverseRequest,
	opts ...option.RequestOption,
) (*sdk.DomainWhoisReverseResponse, error) {
	response, err := c.WithRawResponse.DomainWhoisReverse(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve real-time DNS records for any hostname. Supports multiple record types including A, AAAA, MX, NS, SOA, SPF, TXT, and CNAME records.
func (c *Client) DomainDNSLookup(
	ctx context.Context,
	request *sdk.DomainDNSLookupRequest,
	opts ...option.RequestOption,
) (*sdk.DomainDNSLookupResponse, error) {
	response, err := c.WithRawResponse.DomainDNSLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Perform DNS lookups for multiple hostnames in a single request. Supports up to `100 host-names per request`
// and returns DNS records including A, AAAA, MX, NS, SOA, SPF, TXT, and CNAME records.
func (c *Client) BulkDomainDNSLookup(
	ctx context.Context,
	request *sdk.BulkDomainDNSLookupRequest,
	opts ...option.RequestOption,
) (*sdk.BulkDomainDNSLookupResponse, error) {
	response, err := c.WithRawResponse.BulkDomainDNSLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve historical DNS records for any hostname. Access unique historical data for A, AAAA, MX, NS, SOA, SPF, TXT, and CNAME records,
// including subdomains. Results are paginated with up to 100 unique records per page.
func (c *Client) DomainDNSHistory(
	ctx context.Context,
	request *sdk.DomainDNSHistoryRequest,
	opts ...option.RequestOption,
) (*sdk.DomainDNSHistoryResponse, error) {
	response, err := c.WithRawResponse.DomainDNSHistory(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve all the hostnames associated with any particular A, AAAA, MX, NS, SOA, SPF, TXT, and CNAME DNS records. For instance, you can access all the hostnames hosted on any IP/CIDR notation, all the domain names using Cloudflare name servers, and all the domain names using Google Mailbox
func (c *Client) DomainDNSReverse(
	ctx context.Context,
	request *sdk.DomainDNSReverseRequest,
	opts ...option.RequestOption,
) (*sdk.DomainDNSReverseResponse, error) {
	response, err := c.WithRawResponse.DomainDNSReverse(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Execute a series of web scraping instructions on a target URL.
// Supports various operations like form filling, clicking, data extraction, and CAPTCHA solving.
func (c *Client) WebScrape(
	ctx context.Context,
	request *sdk.WebScrapeRequest,
	opts ...option.RequestOption,
) (*sdk.WebScrapeResponse, error) {
	response, err := c.WithRawResponse.WebScrape(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Validates a single email address and returns result.
func (c *Client) EmailValidate(
	ctx context.Context,
	request *sdk.EmailValidateRequest,
	opts ...option.RequestOption,
) (*sdk.EmailValidateResponse, error) {
	response, err := c.WithRawResponse.EmailValidate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Validates a bulk of email addresses and returns result for each. Maximum `10` email addresses per request.
func (c *Client) BulkEmailValidate(
	ctx context.Context,
	request *sdk.BulkEmailValidateRequest,
	opts ...option.RequestOption,
) (*sdk.BulkEmailValidateResponse, error) {
	response, err := c.WithRawResponse.BulkEmailValidate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Validates a single phone number and returns detailed metadata including carrier, line type, geolocation, time zones, and standardized formats.
func (c *Client) PhoneValidate(
	ctx context.Context,
	request *sdk.PhoneValidateRequest,
	opts ...option.RequestOption,
) (*sdk.PhoneValidateResponse, error) {
	response, err := c.WithRawResponse.PhoneValidate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Validates up to 100 phone numbers in a single request. Each number is processed independently — invalid entries return per-number errors without affecting the rest of the batch.
func (c *Client) BulkPhoneValidate(
	ctx context.Context,
	request *sdk.BulkPhoneValidateRequest,
	opts ...option.RequestOption,
) ([]*sdk.BulkPhoneValidateResponseItem, error) {
	response, err := c.WithRawResponse.BulkPhoneValidate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve comprehensive SSL certificate information without the certificate chain.
// This endpoint provides detailed information about the SSL certificate including expiry dates, issuer details, and encryption methods.
func (c *Client) DomainSslLookup(
	ctx context.Context,
	request *sdk.DomainSslLookupRequest,
	opts ...option.RequestOption,
) (*sdk.DomainSslLookupResponse, error) {
	response, err := c.WithRawResponse.DomainSslLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the complete SSL certificate chain from root Certificate Authority (CA) to end-user certificate.
// This endpoint provides comprehensive information about each certificate in the chain.
func (c *Client) DomainSslChainLookup(
	ctx context.Context,
	request *sdk.DomainSslChainLookupRequest,
	opts ...option.RequestOption,
) (*sdk.DomainSslChainLookupResponse, error) {
	response, err := c.WithRawResponse.DomainSslChainLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The Domain Search API is designed to simplify the process of finding available domain names across all top-level domains (TLDs) and second-level domains (SLDs).
func (c *Client) DomainAvailabilityCheck(
	ctx context.Context,
	request *sdk.DomainAvailabilityCheckRequest,
	opts ...option.RequestOption,
) (*sdk.DomainAvailabilityCheckResponse, error) {
	response, err := c.WithRawResponse.DomainAvailabilityCheck(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Perform Bulk Domain Availability checks using a list of domains. Supports upto `100 Domains Per Request`.
func (c *Client) BulkDomainAvailabilityCheck(
	ctx context.Context,
	request *sdk.BulkDomainAvailabilityCheckRequest,
	opts ...option.RequestOption,
) (*sdk.BulkDomainAvailabilityCheckResponse, error) {
	response, err := c.WithRawResponse.BulkDomainAvailabilityCheck(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The Domain Search API is designed to simplify the process of finding available domain names across all top-level domains (TLDs) and second-level domains (SLDs).
func (c *Client) DomainAvailabilitySuggestions(
	ctx context.Context,
	request *sdk.DomainAvailabilitySuggestionsRequest,
	opts ...option.RequestOption,
) (*sdk.DomainAvailabilitySuggestionsResponse, error) {
	response, err := c.WithRawResponse.DomainAvailabilitySuggestions(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The Subdomain Lookup API is designed to retrieve subdomains related to the given domain name. It helps you explore subdomains that are available for registration or usage.
func (c *Client) SubdomainsLookup(
	ctx context.Context,
	request *sdk.SubdomainsLookupRequest,
	opts ...option.RequestOption,
) (*sdk.SubdomainsLookupResponse, error) {
	response, err := c.WithRawResponse.SubdomainsLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API merges multiple PDF files into a single PDF, in the order they are provided
func (c *Client) PdfMerge(
	ctx context.Context,
	request *sdk.PdfMergeRequest,
	opts ...option.RequestOption,
) (*sdk.PdfMergeResponse, error) {
	response, err := c.WithRawResponse.PdfMerge(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API removes a selection or range of pages from a PDF file.
func (c *Client) PdfRemovePages(
	ctx context.Context,
	request *sdk.PdfRemovePagesRequest,
	opts ...option.RequestOption,
) (*sdk.PdfRemovePagesResponse, error) {
	response, err := c.WithRawResponse.PdfRemovePages(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API splits a PDF into multiple parts based on specified page numbers or ranges.
func (c *Client) PdfSplit(
	ctx context.Context,
	request *sdk.PdfSplitRequest,
	opts ...option.RequestOption,
) (*sdk.PdfSplitResponse, error) {
	response, err := c.WithRawResponse.PdfSplit(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API rotates pages of a PDF by a specified angle (in multiples of 90 degrees).
func (c *Client) PdfRotate(
	ctx context.Context,
	request *sdk.PdfRotateRequest,
	opts ...option.RequestOption,
) (*sdk.PdfRotateResponse, error) {
	response, err := c.WithRawResponse.PdfRotate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API compresses a given PDF file to reduce its file size.
func (c *Client) PdfCompress(
	ctx context.Context,
	request *sdk.PdfCompressRequest,
	opts ...option.RequestOption,
) (*sdk.PdfCompressResponse, error) {
	response, err := c.WithRawResponse.PdfCompress(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API extracts specific pages or page ranges from a PDF file and returns them as a new PDF.
func (c *Client) PdfExtractPages(
	ctx context.Context,
	request *sdk.PdfExtractPagesRequest,
	opts ...option.RequestOption,
) (*sdk.PdfExtractPagesResponse, error) {
	response, err := c.WithRawResponse.PdfExtractPages(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// API endpoint that linearizes any given PDF, restructuring it for faster loading and page-by-page viewing in web browsers.
func (c *Client) PdfLinearize(
	ctx context.Context,
	request *sdk.PdfLinearizeRequest,
	opts ...option.RequestOption,
) (*sdk.PdfLinearizeResponse, error) {
	response, err := c.WithRawResponse.PdfLinearize(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API encrypts a PDF file by setting a password required to open it.
func (c *Client) PdfEncrypt(
	ctx context.Context,
	request *sdk.PdfEncryptRequest,
	opts ...option.RequestOption,
) (*sdk.PdfEncryptResponse, error) {
	response, err := c.WithRawResponse.PdfEncrypt(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API decrypts PDF files, removing all encryption, including open passwords and permission restrictions.
func (c *Client) PdfDecrypt(
	ctx context.Context,
	request *sdk.PdfDecryptRequest,
	opts ...option.RequestOption,
) (*sdk.PdfDecryptResponse, error) {
	response, err := c.WithRawResponse.PdfDecrypt(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API applies permission restrictions on a PDF file, such as disabling printing, copying, or editing. This can include password protection to enforce restrictions.
func (c *Client) PdfRestrict(
	ctx context.Context,
	request *sdk.PdfRestrictRequest,
	opts ...option.RequestOption,
) (*sdk.PdfRestrictResponse, error) {
	response, err := c.WithRawResponse.PdfRestrict(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API removes permission restrictions from a PDF while keeping it encrypted. If you want to remove all security (including encryption), use the `/pdf/decrypt` endpoint instead.
func (c *Client) PdfUnrestrict(
	ctx context.Context,
	request *sdk.PdfUnrestrictRequest,
	opts ...option.RequestOption,
) (*sdk.PdfUnrestrictResponse, error) {
	response, err := c.WithRawResponse.PdfUnrestrict(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API converts a given PDF file into a sequence of PNG images.
func (c *Client) PdfConvertToPng(
	ctx context.Context,
	request *sdk.PdfConvertToPngRequest,
	opts ...option.RequestOption,
) (*sdk.PdfConvertToPngResponse, error) {
	response, err := c.WithRawResponse.PdfConvertToPng(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API converts a given PDF file into a sequence of JPG images.
func (c *Client) PdfConvertToJpg(
	ctx context.Context,
	request *sdk.PdfConvertToJpgRequest,
	opts ...option.RequestOption,
) (*sdk.PdfConvertToJpgResponse, error) {
	response, err := c.WithRawResponse.PdfConvertToJpg(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API converts a given PDF file into a sequence of TIFF images. The output images can be saved as a single TIFF file, or as a sequence of TIFF files.
func (c *Client) PdfConvertToTiff(
	ctx context.Context,
	request *sdk.PdfConvertToTiffRequest,
	opts ...option.RequestOption,
) (*sdk.PdfConvertToTiffResponse, error) {
	response, err := c.WithRawResponse.PdfConvertToTiff(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Converts a PDF file to a BMP image.
func (c *Client) PdfConvertToBmp(
	ctx context.Context,
	request *sdk.PdfConvertToBmpRequest,
	opts ...option.RequestOption,
) (*sdk.PdfConvertToBmpResponse, error) {
	response, err := c.WithRawResponse.PdfConvertToBmp(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API converts a given PDF file into a sequence of GIF images.
func (c *Client) PdfConvertToGif(
	ctx context.Context,
	request *sdk.PdfConvertToGifRequest,
	opts ...option.RequestOption,
) (*sdk.PdfConvertToGifResponse, error) {
	response, err := c.WithRawResponse.PdfConvertToGif(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API uploads multiple PDF files to the API Freaks server and generates their unique file IDs.
func (c *Client) PdfUploadResources(
	ctx context.Context,
	request *sdk.PdfUploadResourcesRequest,
	opts ...option.RequestOption,
) (*sdk.PdfUploadResourcesResponse, error) {
	response, err := c.WithRawResponse.PdfUploadResources(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API uploads PDF files to the API Freaks server in binary format.
func (c *Client) PdfUploadBinary(
	ctx context.Context,
	request *sdk.PdfUploadBinaryRequest,
	opts ...option.RequestOption,
) (*sdk.PdfUploadBinaryResponse, error) {
	response, err := c.WithRawResponse.PdfUploadBinary(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API downloads PDF files or ZIP archives from the server using their unique resource ID.
func (c *Client) PdfDownloadResource(
	ctx context.Context,
	request *sdk.PdfDownloadResourceRequest,
	opts ...option.RequestOption,
) (io.Reader, error) {
	response, err := c.WithRawResponse.PdfDownloadResource(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API checks the status of a previously initiated PDF processing task using its unique task ID.
func (c *Client) PdfGetTaskStatus(
	ctx context.Context,
	request *sdk.PdfGetTaskStatusRequest,
	opts ...option.RequestOption,
) (*sdk.PdfGetTaskStatusResponse, error) {
	response, err := c.WithRawResponse.PdfGetTaskStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API checks the status of a PDF file using its unique file ID, providing information about its creation and potential deletion time.
func (c *Client) PdfGetFileStatus(
	ctx context.Context,
	request *sdk.PdfGetFileStatusRequest,
	opts ...option.RequestOption,
) (*sdk.PdfGetFileStatusResponse, error) {
	response, err := c.WithRawResponse.PdfGetFileStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API retrieves a list of all PDF files uploaded and generated by a specific user. Please note that if the user is part of an organization, only the Organization Administrator can access this endpoint. Organization Members cannot access this endpoint.
func (c *Client) PdfListFiles(
	ctx context.Context,
	request *sdk.PdfListFilesRequest,
	opts ...option.RequestOption,
) (*sdk.PdfListFilesResponse, error) {
	response, err := c.WithRawResponse.PdfListFiles(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// This API deletes a PDF file using its unique file ID.
func (c *Client) PdfDeleteFile(
	ctx context.Context,
	request *sdk.PdfDeleteFileRequest,
	opts ...option.RequestOption,
) (*sdk.PdfDeleteFileResponse, error) {
	response, err := c.WithRawResponse.PdfDeleteFile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Capture full-page screenshots and videos of websites with advanced options like device simulation, custom code injection, cookie banner blocking, and scrollable content recording.
// Supports multiple output formats including JSON, image, GIF, MP4, and WebM.
func (c *Client) ScreenshotCapture(
	ctx context.Context,
	request *sdk.ScreenshotCaptureRequest,
	opts ...option.RequestOption,
) (io.Reader, error) {
	response, err := c.WithRawResponse.ScreenshotCapture(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Our Bulk Screenshot API allows you to capture screenshots of multiple webpages simultaneously, saving you time and effort. Instead of manually capturing each page one by one, you can batch process URLs and receive high-quality screenshots in the format you choose.
//
//	Maximum `50 URLs` per request.
func (c *Client) BulkScreenshotCapture(
	ctx context.Context,
	request *sdk.BulkScreenshotCaptureRequest,
	opts ...option.RequestOption,
) (*sdk.BulkScreenshotCaptureResponse, error) {
	response, err := c.WithRawResponse.BulkScreenshotCapture(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get live forex rates for all world currencies with customizable update frequency
func (c *Client) CurrencyLatestRates(
	ctx context.Context,
	request *sdk.CurrencyLatestRatesRequest,
	opts ...option.RequestOption,
) (*sdk.CurrencyLatestRatesResponse, error) {
	response, err := c.WithRawResponse.CurrencyLatestRates(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get historical exchange rates for any specific date
func (c *Client) CurrencyHistoricalRates(
	ctx context.Context,
	request *sdk.CurrencyHistoricalRatesRequest,
	opts ...option.RequestOption,
) (*sdk.CurrencyHistoricalRatesResponse, error) {
	response, err := c.WithRawResponse.CurrencyHistoricalRates(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Convert amount between currencies using the latest exchange rates
func (c *Client) CurrencyConvertLatest(
	ctx context.Context,
	request *sdk.CurrencyConvertLatestRequest,
	opts ...option.RequestOption,
) (*sdk.CurrencyConvertLatestResponse, error) {
	response, err := c.WithRawResponse.CurrencyConvertLatest(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Convert amount between currencies using historical rates
func (c *Client) CurrencyConvertHistorical(
	ctx context.Context,
	request *sdk.CurrencyConvertHistoricalRequest,
	opts ...option.RequestOption,
) (*sdk.CurrencyConvertHistoricalResponse, error) {
	response, err := c.WithRawResponse.CurrencyConvertHistorical(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get exchange rates for a time range
func (c *Client) CurrencyTimeSeries(
	ctx context.Context,
	request *sdk.CurrencyTimeSeriesRequest,
	opts ...option.RequestOption,
) (*sdk.CurrencyTimeSeriesResponse, error) {
	response, err := c.WithRawResponse.CurrencyTimeSeries(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get currency fluctuation data for a time period
func (c *Client) CurrencyFluctuation(
	ctx context.Context,
	request *sdk.CurrencyFluctuationRequest,
	opts ...option.RequestOption,
) (*sdk.CurrencyFluctuationResponse, error) {
	response, err := c.WithRawResponse.CurrencyFluctuation(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Convert amount using user's location
func (c *Client) CurrencyConvertByIP(
	ctx context.Context,
	request *sdk.CurrencyConvertByIPRequest,
	opts ...option.RequestOption,
) (*sdk.CurrencyConvertByIPResponse, error) {
	response, err := c.WithRawResponse.CurrencyConvertByIP(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get list of all supported currencies with their metadata
func (c *Client) CurrencySupported(
	ctx context.Context,
	request *sdk.CurrencySupportedRequest,
	opts ...option.RequestOption,
) (*sdk.CurrencySupportedResponse, error) {
	response, err := c.WithRawResponse.CurrencySupported(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get currency symbols and codes
func (c *Client) CurrencySymbols(
	ctx context.Context,
	request *sdk.CurrencySymbolsRequest,
	opts ...option.RequestOption,
) (*sdk.CurrencySymbolsResponse, error) {
	response, err := c.WithRawResponse.CurrencySymbols(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get information about historical data availability and limits
func (c *Client) CurrencyHistoricalLimits(
	ctx context.Context,
	request *sdk.CurrencyHistoricalLimitsRequest,
	opts ...option.RequestOption,
) (*sdk.CurrencyHistoricalLimitsResponse, error) {
	response, err := c.WithRawResponse.CurrencyHistoricalLimits(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get live commodity rates with customizable update frequency
func (c *Client) CommodityLatestRates(
	ctx context.Context,
	request *sdk.CommodityLatestRatesRequest,
	opts ...option.RequestOption,
) (*sdk.CommodityLatestRatesResponse, error) {
	response, err := c.WithRawResponse.CommodityLatestRates(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get historical commodity rates for a specific date
func (c *Client) CommodityHistoricalRates(
	ctx context.Context,
	request *sdk.CommodityHistoricalRatesRequest,
	opts ...option.RequestOption,
) (*sdk.CommodityHistoricalRatesResponse, error) {
	response, err := c.WithRawResponse.CommodityHistoricalRates(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get commodity price fluctuation data for a time period
func (c *Client) CommodityFluctuation(
	ctx context.Context,
	request *sdk.CommodityFluctuationRequest,
	opts ...option.RequestOption,
) (*sdk.CommodityFluctuationResponse, error) {
	response, err := c.WithRawResponse.CommodityFluctuation(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get commodity rates for a time range
func (c *Client) CommodityTimeSeries(
	ctx context.Context,
	request *sdk.CommodityTimeSeriesRequest,
	opts ...option.RequestOption,
) (*sdk.CommodityTimeSeriesResponse, error) {
	response, err := c.WithRawResponse.CommodityTimeSeries(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get list of supported commodities
func (c *Client) CommoditySymbols(
	ctx context.Context,
	request *sdk.CommoditySymbolsRequest,
	opts ...option.RequestOption,
) (*sdk.CommoditySymbolsResponse, error) {
	response, err := c.WithRawResponse.CommoditySymbols(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieves a list of supported countries.
func (c *Client) VatSupportedCountries(
	ctx context.Context,
	request *sdk.VatSupportedCountriesRequest,
	opts ...option.RequestOption,
) (*sdk.VatSupportedCountriesResponse, error) {
	response, err := c.WithRawResponse.VatSupportedCountries(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Fetches VAT rate based on the specified or originating IP address.
func (c *Client) VatRateByIP(
	ctx context.Context,
	request *sdk.VatRateByIPRequest,
	opts ...option.RequestOption,
) ([]*sdk.VatRateByIPResponseItem, error) {
	response, err := c.WithRawResponse.VatRateByIP(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Fetches VAT rates for a single country or state provided via query parameters.
func (c *Client) VatRateByCountry(
	ctx context.Context,
	request *sdk.VatRateByCountryRequest,
	opts ...option.RequestOption,
) ([]*sdk.VatRateByCountryResponseItem, error) {
	response, err := c.WithRawResponse.VatRateByCountry(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieves VAT details for multiple countries or country-state combinations in a single request. Maximum of `100` entries per request are allowed.
func (c *Client) BulkVatRateByCountry(
	ctx context.Context,
	request *sdk.BulkVatRateByCountryRequest,
	opts ...option.RequestOption,
) (*sdk.BulkVatRateByCountryResponse, error) {
	response, err := c.WithRawResponse.BulkVatRateByCountry(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Validates an EU or UK VAT number and returns registration status details.
func (c *Client) VatValidate(
	ctx context.Context,
	request *sdk.VatValidateRequest,
	opts ...option.RequestOption,
) (*sdk.VatValidateResponse, error) {
	response, err := c.WithRawResponse.VatValidate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Checks an IBAN for structural validity, checksum accuracy, and bank metadata.
func (c *Client) IbanValidate(
	ctx context.Context,
	request *sdk.IbanValidateRequest,
	opts ...option.RequestOption,
) (*sdk.IbanValidateResponse, error) {
	response, err := c.WithRawResponse.IbanValidate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Fetches SWIFT codes for a given country, bank, and city.
func (c *Client) SwiftCodeFind(
	ctx context.Context,
	request *sdk.SwiftCodeFindRequest,
	opts ...option.RequestOption,
) ([]string, error) {
	response, err := c.WithRawResponse.SwiftCodeFind(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Fetches detailed information about a SWIFT code.
func (c *Client) SwiftCodeLookup(
	ctx context.Context,
	request *sdk.SwiftCodeLookupRequest,
	opts ...option.RequestOption,
) (*sdk.SwiftCodeLookupResponse, error) {
	response, err := c.WithRawResponse.SwiftCodeLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ZipcodeLookup(
	ctx context.Context,
	request *sdk.ZipcodeLookupRequest,
	opts ...option.RequestOption,
) (*sdk.ZipcodeLookupResponse, error) {
	response, err := c.WithRawResponse.ZipcodeLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Validates a bulk of ZIP/postal codes and returns result for each. Maximum `100` ZIP/postal codes per request.
func (c *Client) BulkZipcodeLookup(
	ctx context.Context,
	request *sdk.BulkZipcodeLookupRequest,
	opts ...option.RequestOption,
) (*sdk.BulkZipcodeLookupResponse, error) {
	response, err := c.WithRawResponse.BulkZipcodeLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ZipcodeSearchByCity(
	ctx context.Context,
	request *sdk.ZipcodeSearchByCityRequest,
	opts ...option.RequestOption,
) (*sdk.ZipcodeSearchByCityResponse, error) {
	response, err := c.WithRawResponse.ZipcodeSearchByCity(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ZipcodeSearchByRegion(
	ctx context.Context,
	request *sdk.ZipcodeSearchByRegionRequest,
	opts ...option.RequestOption,
) (*sdk.ZipcodeSearchByRegionResponse, error) {
	response, err := c.WithRawResponse.ZipcodeSearchByRegion(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ZipcodeSearchByRadius(
	ctx context.Context,
	request *sdk.ZipcodeSearchByRadiusRequest,
	opts ...option.RequestOption,
) (*sdk.ZipcodeSearchByRadiusResponse, error) {
	response, err := c.WithRawResponse.ZipcodeSearchByRadius(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get distance between postal codes. Maximum `100` postal codes per request.
func (c *Client) ZipcodeDistance(
	ctx context.Context,
	request *sdk.ZipcodeDistanceRequest,
	opts ...option.RequestOption,
) (*sdk.ZipcodeDistanceResponse, error) {
	response, err := c.WithRawResponse.ZipcodeDistance(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get matching ZIP/postal code pairs within a specified distance. Maximum `100` postal codes per request.
func (c *Client) ZipcodeDistanceMatch(
	ctx context.Context,
	request *sdk.ZipcodeDistanceMatchRequest,
	opts ...option.RequestOption,
) (*sdk.ZipcodeDistanceMatchResponse, error) {
	response, err := c.WithRawResponse.ZipcodeDistanceMatch(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get current weather data including temperature, humidity, precipitation, wind conditions, atmospheric pressure, and air quality for any location. Accepts city names, coordinates, or IP addresses. Also includes astronomy data and timezone-aware timestamps.
func (c *Client) CurrentWeather(
	ctx context.Context,
	request *sdk.CurrentWeatherRequest,
	opts ...option.RequestOption,
) (*sdk.CurrentWeatherResponse, error) {
	response, err := c.WithRawResponse.CurrentWeather(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve current weather conditions for up to `50 locations` in a single request. A maximum of 50 locations (city names, IP addresses, or geographic coordinates) can be included in the request body.
func (c *Client) BulkCurrentWeather(
	ctx context.Context,
	request *sdk.BulkCurrentWeatherRequest,
	opts ...option.RequestOption,
) (*sdk.BulkCurrentWeatherResponse, error) {
	response, err := c.WithRawResponse.BulkCurrentWeather(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Access comprehensive weather forecasts with customizable precision - choose from daily overviews, hourly breakdowns, or even minute-by-minute data. Configure your date ranges or use the default 7-day forecast for standard weather planning.
func (c *Client) WeatherForecast(
	ctx context.Context,
	request *sdk.WeatherForecastRequest,
	opts ...option.RequestOption,
) (*sdk.WeatherForecastResponse, error) {
	response, err := c.WithRawResponse.WeatherForecast(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Access past weather conditions for specific dates with records going back to 1940. Retrieve comprehensive historical data with both daily and hourly precision options.
func (c *Client) HistoricalWeather(
	ctx context.Context,
	request *sdk.HistoricalWeatherRequest,
	opts ...option.RequestOption,
) (*sdk.HistoricalWeatherResponse, error) {
	response, err := c.WithRawResponse.HistoricalWeather(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Pull historical weather information for date ranges up to 90 days (daily data) or 7 days (hourly data). Get consistent formatting across your specified date range with reliable historical weather patterns.
func (c *Client) WeatherTimeSeries(
	ctx context.Context,
	request *sdk.WeatherTimeSeriesRequest,
	opts ...option.RequestOption,
) (*sdk.WeatherTimeSeriesResponse, error) {
	response, err := c.WithRawResponse.WeatherTimeSeries(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Provides hourly forecasts of marine conditions including wave heights, wave directions, wave periods, swell info, sea surface temperatures, and ocean currents. Supports multiple geographical points and returns daily max wave statistics for up to 7 days. Ideal for maritime planning, navigation, and coastal activities.
func (c *Client) MarineWeather(
	ctx context.Context,
	request *sdk.MarineWeatherRequest,
	opts ...option.RequestOption,
) (*sdk.MarineWeatherResponse, error) {
	response, err := c.WithRawResponse.MarineWeather(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Monitor and predict air quality conditions using European and US AQI standards. Track pollutant concentrations including PM10, PM2.5, carbon monoxide, nitrogen dioxide, sulfur dioxide, ozone, and dust particles. Get current readings plus hourly forecasts up to 5 days ahead, complete with UV index and aerosol measurements for comprehensive air quality assessment.
func (c *Client) AirQuality(
	ctx context.Context,
	request *sdk.AirQualityRequest,
	opts ...option.RequestOption,
) (*sdk.AirQualityResponse, error) {
	response, err := c.WithRawResponse.AirQuality(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Provides flood forecast data for a given location, including river discharge metrics such as mean, median, maximum, minimum, and percentile values (p25, p75). Requires a startDate and endDate, with the date range limited to 16 days. Location can be specified using city name, latitude/longitude, or IP address.
func (c *Client) FloodForecast(
	ctx context.Context,
	request *sdk.FloodForecastRequest,
	opts ...option.RequestOption,
) (*sdk.FloodForecastResponse, error) {
	response, err := c.WithRawResponse.FloodForecast(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve countries, optionally filtered by region or subregion.
func (c *Client) GetCountries(
	ctx context.Context,
	request *sdk.GetCountriesRequest,
	opts ...option.RequestOption,
) (*sdk.GetCountriesResponse, error) {
	response, err := c.WithRawResponse.GetCountries(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetCountryDetails(
	ctx context.Context,
	request *sdk.GetCountryDetailsRequest,
	opts ...option.RequestOption,
) (*sdk.GetCountryDetailsResponse, error) {
	response, err := c.WithRawResponse.GetCountryDetails(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetRegions(
	ctx context.Context,
	request *sdk.GetRegionsRequest,
	opts ...option.RequestOption,
) (*sdk.GetRegionsResponse, error) {
	response, err := c.WithRawResponse.GetRegions(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetSubregions(
	ctx context.Context,
	request *sdk.GetSubregionsRequest,
	opts ...option.RequestOption,
) (*sdk.GetSubregionsResponse, error) {
	response, err := c.WithRawResponse.GetSubregions(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve administrative units based on ISO 3166-1 alpha-2 country code.
func (c *Client) GetAdminLevels(
	ctx context.Context,
	request *sdk.GetAdminLevelsRequest,
	opts ...option.RequestOption,
) (*sdk.GetAdminLevelsResponse, error) {
	response, err := c.WithRawResponse.GetAdminLevels(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve administrative divisions for a given country using ISO 3166-1 alpha-2 country codes. You can optionally filter by administrative levels.
func (c *Client) GetAdminUnits(
	ctx context.Context,
	request *sdk.GetAdminUnitsRequest,
	opts ...option.RequestOption,
) (*sdk.GetAdminUnitsResponse, error) {
	response, err := c.WithRawResponse.GetAdminUnits(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve detailed administrative unit information by country and optionally filtered by admin code.
func (c *Client) GetAdminUnitDetails(
	ctx context.Context,
	request *sdk.GetAdminUnitDetailsRequest,
	opts ...option.RequestOption,
) (*sdk.GetAdminUnitDetailsResponse, error) {
	response, err := c.WithRawResponse.GetAdminUnitDetails(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a list of cities within a country, optionally filtered by an administrative unit code.
func (c *Client) GetCities(
	ctx context.Context,
	request *sdk.GetCitiesRequest,
	opts ...option.RequestOption,
) (*sdk.GetCitiesResponse, error) {
	response, err := c.WithRawResponse.GetCities(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Get list of all supported flags with their metadata
func (c *Client) GetSupportedFlags(
	ctx context.Context,
	request *sdk.GetSupportedFlagsRequest,
	opts ...option.RequestOption,
) ([]*sdk.GetSupportedFlagsResponseItem, error) {
	response, err := c.WithRawResponse.GetSupportedFlags(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the flag for a specific country
func (c *Client) GetFlags(
	ctx context.Context,
	request *sdk.GetFlagsRequest,
	opts ...option.RequestOption,
) (io.Reader, error) {
	response, err := c.WithRawResponse.GetFlags(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve current time, date, and timezone-related information by specifying a timezone name, location address, location coordinates, IP address, or use the client IP address if no parameter is passed.
func (c *Client) TimezoneLookup(
	ctx context.Context,
	request *sdk.TimezoneLookupRequest,
	opts ...option.RequestOption,
) (*sdk.TimezoneLookupResponse, error) {
	response, err := c.WithRawResponse.TimezoneLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Converts a given time from one timezone to another using various input types like timezone name, coordinates, location, or codes.
func (c *Client) TimezoneConvert(
	ctx context.Context,
	request *sdk.TimezoneConvertRequest,
	opts ...option.RequestOption,
) (*sdk.TimezoneConvertResponse, error) {
	response, err := c.WithRawResponse.TimezoneConvert(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Parse User Agent string to get detailed browser, device, and operating system information
func (c *Client) UserAgentLookup(
	ctx context.Context,
	request *sdk.UserAgentLookupRequest,
	opts ...option.RequestOption,
) (*sdk.UserAgentLookupResponse, error) {
	response, err := c.WithRawResponse.UserAgentLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Parse up to `50,000 User-Agent strings` at once in a single request.
func (c *Client) BulkUserAgentLookup(
	ctx context.Context,
	request *sdk.BulkUserAgentLookupRequest,
	opts ...option.RequestOption,
) ([]*sdk.BulkUserAgentLookupResponseItem, error) {
	response, err := c.WithRawResponse.BulkUserAgentLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Perform Optical Character Recognition (OCR) on images, PDFs, or ZIP archives. Supports two models: `mini-ocr-v1` for CAPTCHA-optimized OCR and `ocr-v1` for general-purpose document text extraction. Supports zonal OCR to extract text from specific regions of an image.
//
// **Notes:**
// - The `zone` query parameter cannot be given with .pdf and .zip types as it can only be applied to single image query.
// - The `page_range` query parameter cannot be given in any other type except .pdf types.
// - PDFs containing images in them are allowed only for processing.
// - The `mini-ocr-v1` model doesn’t support the following query parameters:
//   - `page_range` (.pdf types)
//   - `zone`
func (c *Client) OcrPredict(
	ctx context.Context,
	request *sdk.OcrPredictRequest,
	opts ...option.RequestOption,
) (*sdk.OcrPredictResponse, error) {
	response, err := c.WithRawResponse.OcrPredict(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Analyze text for grammar errors and return the exact words flagged as grammatically incorrect with zero-based word positions.
func (c *Client) GrammarDetect(
	ctx context.Context,
	request *sdk.GrammarDetectRequest,
	opts ...option.RequestOption,
) (*sdk.GrammarDetectResponse, error) {
	response, err := c.WithRawResponse.GrammarDetect(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Submit text with grammatical issues and receive a clean grammar-corrected result for proofreading and content workflows.
func (c *Client) GrammarCorrect(
	ctx context.Context,
	request *sdk.GrammarCorrectRequest,
	opts ...option.RequestOption,
) (*sdk.GrammarCorrectResponse, error) {
	response, err := c.WithRawResponse.GrammarCorrect(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Analyze text and return weak, vague, or filler words with zero-based word positions to help writers produce clearer and more concise content.
func (c *Client) WeakWordsDetect(
	ctx context.Context,
	request *sdk.WeakWordsDetectRequest,
	opts ...option.RequestOption,
) (*sdk.WeakWordsDetectResponse, error) {
	response, err := c.WithRawResponse.WeakWordsDetect(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Analyze text readability using industry-standard formulas including Flesch Reading Ease, Flesch-Kincaid Grade Level, Gunning Fog Index, SMOG Index, Coleman-Liau Index, and Automated Readability Index.
func (c *Client) ReadabilityScore(
	ctx context.Context,
	request *sdk.ReadabilityScoreRequest,
	opts ...option.RequestOption,
) (*sdk.ReadabilityScoreResponse, error) {
	response, err := c.WithRawResponse.ReadabilityScore(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve sunrise and sunset times, current position of the moon, and other related information by specifying a location address, location coordinates, IP address, or using the client IP address if no parameter is passed.
func (c *Client) AstronomyLookup(
	ctx context.Context,
	request *sdk.AstronomyLookupRequest,
	opts ...option.RequestOption,
) (*sdk.AstronomyLookupResponse, error) {
	response, err := c.WithRawResponse.AstronomyLookup(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
