// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	core "github.com/api-freaks/sdk/core"
)

// Bad Request
type BadRequestError struct {
	*core.APIError
	Body any
}

func (b *BadRequestError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.StatusCode = 400
	b.Body = body
	return nil
}

func (b *BadRequestError) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

func (b *BadRequestError) Unwrap() error {
	return b.APIError
}

// Payload Too Large
type ContentTooLargeError struct {
	*core.APIError
	Body any
}

func (c *ContentTooLargeError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.StatusCode = 413
	c.Body = body
	return nil
}

func (c *ContentTooLargeError) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

func (c *ContentTooLargeError) Unwrap() error {
	return c.APIError
}

// Forbidden
type ForbiddenError struct {
	*core.APIError
	Body any
}

func (f *ForbiddenError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	f.StatusCode = 403
	f.Body = body
	return nil
}

func (f *ForbiddenError) MarshalJSON() ([]byte, error) {
	return json.Marshal(f.Body)
}

func (f *ForbiddenError) Unwrap() error {
	return f.APIError
}

// Gateway Timeout
type GatewayTimeoutError struct {
	*core.APIError
	Body any
}

func (g *GatewayTimeoutError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	g.StatusCode = 504
	g.Body = body
	return nil
}

func (g *GatewayTimeoutError) MarshalJSON() ([]byte, error) {
	return json.Marshal(g.Body)
}

func (g *GatewayTimeoutError) Unwrap() error {
	return g.APIError
}

// Internal Server Error
type InternalServerError struct {
	*core.APIError
	Body any
}

func (i *InternalServerError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	i.StatusCode = 500
	i.Body = body
	return nil
}

func (i *InternalServerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.Body)
}

func (i *InternalServerError) Unwrap() error {
	return i.APIError
}

// Locked
type LockedError struct {
	*core.APIError
	Body any
}

func (l *LockedError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	l.StatusCode = 423
	l.Body = body
	return nil
}

func (l *LockedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(l.Body)
}

func (l *LockedError) Unwrap() error {
	return l.APIError
}

// Wrong HTTP method was used on the endpoint.
type MethodNotAllowedError struct {
	*core.APIError
	Body *MethodNotAllowedErrorBody
}

func (m *MethodNotAllowedError) UnmarshalJSON(data []byte) error {
	var body *MethodNotAllowedErrorBody
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	m.StatusCode = 405
	m.Body = body
	return nil
}

func (m *MethodNotAllowedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(m.Body)
}

func (m *MethodNotAllowedError) Unwrap() error {
	return m.APIError
}

// Server terminated connection unexpectedly.
type NoResponseError struct {
	*core.APIError
	Body *NoResponseErrorBody
}

func (n *NoResponseError) UnmarshalJSON(data []byte) error {
	var body *NoResponseErrorBody
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.StatusCode = 444
	n.Body = body
	return nil
}

func (n *NoResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}

func (n *NoResponseError) Unwrap() error {
	return n.APIError
}

// Not Acceptable
type NotAcceptableError struct {
	*core.APIError
	Body any
}

func (n *NotAcceptableError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.StatusCode = 406
	n.Body = body
	return nil
}

func (n *NotAcceptableError) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}

func (n *NotAcceptableError) Unwrap() error {
	return n.APIError
}

// Not Found
type NotFoundError struct {
	*core.APIError
	Body any
}

func (n *NotFoundError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.StatusCode = 404
	n.Body = body
	return nil
}

func (n *NotFoundError) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}

func (n *NotFoundError) Unwrap() error {
	return n.APIError
}

// Payment Required
type PaymentRequiredError struct {
	*core.APIError
	Body any
}

func (p *PaymentRequiredError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	p.StatusCode = 402
	p.Body = body
	return nil
}

func (p *PaymentRequiredError) MarshalJSON() ([]byte, error) {
	return json.Marshal(p.Body)
}

func (p *PaymentRequiredError) Unwrap() error {
	return p.APIError
}

// Tunnel connection failed.
type ProxyAuthenticationRequiredError struct {
	*core.APIError
	Body *ProxyAuthenticationRequiredErrorBody
}

func (p *ProxyAuthenticationRequiredError) UnmarshalJSON(data []byte) error {
	var body *ProxyAuthenticationRequiredErrorBody
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	p.StatusCode = 407
	p.Body = body
	return nil
}

func (p *ProxyAuthenticationRequiredError) MarshalJSON() ([]byte, error) {
	return json.Marshal(p.Body)
}

func (p *ProxyAuthenticationRequiredError) Unwrap() error {
	return p.APIError
}

// Request Timeout – WHOIS data could not be fetched
type RequestTimeoutError struct {
	*core.APIError
	Body any
}

func (r *RequestTimeoutError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	r.StatusCode = 408
	r.Body = body
	return nil
}

func (r *RequestTimeoutError) MarshalJSON() ([]byte, error) {
	return json.Marshal(r.Body)
}

func (r *RequestTimeoutError) Unwrap() error {
	return r.APIError
}

// Service Unavailable
type ServiceUnavailableError struct {
	*core.APIError
	Body any
}

func (s *ServiceUnavailableError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	s.StatusCode = 503
	s.Body = body
	return nil
}

func (s *ServiceUnavailableError) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.Body)
}

func (s *ServiceUnavailableError) Unwrap() error {
	return s.APIError
}

// Too Many Requests
type TooManyRequestsError struct {
	*core.APIError
	Body any
}

func (t *TooManyRequestsError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	t.StatusCode = 429
	t.Body = body
	return nil
}

func (t *TooManyRequestsError) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}

func (t *TooManyRequestsError) Unwrap() error {
	return t.APIError
}

// Unauthorized
type UnauthorizedError struct {
	*core.APIError
	Body any
}

func (u *UnauthorizedError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 401
	u.Body = body
	return nil
}

func (u *UnauthorizedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnauthorizedError) Unwrap() error {
	return u.APIError
}

// Unsupported File Type
type UnsupportedMediaTypeError struct {
	*core.APIError
	Body any
}

func (u *UnsupportedMediaTypeError) UnmarshalJSON(data []byte) error {
	var body any
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 415
	u.Body = body
	return nil
}

func (u *UnsupportedMediaTypeError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnsupportedMediaTypeError) Unwrap() error {
	return u.APIError
}
