// Code generated by Fern. DO NOT EDIT.

package api

import (
	core "github.com/api-freaks/sdk/core"
	internal "github.com/api-freaks/sdk/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	400: func(apiError *core.APIError) error {
		return &BadRequestError{
			APIError: apiError,
		}
	},
	401: func(apiError *core.APIError) error {
		return &UnauthorizedError{
			APIError: apiError,
		}
	},
	402: func(apiError *core.APIError) error {
		return &PaymentRequiredError{
			APIError: apiError,
		}
	},
	403: func(apiError *core.APIError) error {
		return &ForbiddenError{
			APIError: apiError,
		}
	},
	404: func(apiError *core.APIError) error {
		return &NotFoundError{
			APIError: apiError,
		}
	},
	406: func(apiError *core.APIError) error {
		return &NotAcceptableError{
			APIError: apiError,
		}
	},
	413: func(apiError *core.APIError) error {
		return &ContentTooLargeError{
			APIError: apiError,
		}
	},
	423: func(apiError *core.APIError) error {
		return &LockedError{
			APIError: apiError,
		}
	},
	429: func(apiError *core.APIError) error {
		return &TooManyRequestsError{
			APIError: apiError,
		}
	},
	500: func(apiError *core.APIError) error {
		return &InternalServerError{
			APIError: apiError,
		}
	},
	503: func(apiError *core.APIError) error {
		return &ServiceUnavailableError{
			APIError: apiError,
		}
	},
	504: func(apiError *core.APIError) error {
		return &GatewayTimeoutError{
			APIError: apiError,
		}
	},
	408: func(apiError *core.APIError) error {
		return &RequestTimeoutError{
			APIError: apiError,
		}
	},
	405: func(apiError *core.APIError) error {
		return &MethodNotAllowedError{
			APIError: apiError,
		}
	},
	415: func(apiError *core.APIError) error {
		return &UnsupportedMediaTypeError{
			APIError: apiError,
		}
	},
	407: func(apiError *core.APIError) error {
		return &ProxyAuthenticationRequiredError{
			APIError: apiError,
		}
	},
	444: func(apiError *core.APIError) error {
		return &NoResponseError{
			APIError: apiError,
		}
	},
}
