// Code generated by Fern. DO NOT EDIT.

package root_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	strings "strings"
	testing "testing"

	afgosdk "github.com/api-freaks/af-go-sdk"
	client "github.com/api-freaks/af-go-sdk/client"
	option "github.com/api-freaks/af-go-sdk/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestGeolocationLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.GeolocationLookupRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.GeolocationLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestGeolocationLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestGeolocationLookupWithWireMock", "GET", "/v1.0/geolocation/lookup", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestBulkGeolocationLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.BulkGeolocationLookupRequest{
		APIKey: "apiKey",
		Ips: []string{
			"ips",
		},
	}
	_, invocationErr := client.BulkGeolocationLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBulkGeolocationLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBulkGeolocationLookupWithWireMock", "POST", "/v1.0/geolocation/lookup", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestIPSecurityLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.IPSecurityLookupRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.IPSecurityLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestIPSecurityLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestIPSecurityLookupWithWireMock", "GET", "/v1.0/ip/security", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestBulkIPSecurityLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.BulkIPSecurityLookupRequest{
		APIKey: "apiKey",
		Ips: []string{
			"ips",
		},
	}
	_, invocationErr := client.BulkIPSecurityLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBulkIPSecurityLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBulkIPSecurityLookupWithWireMock", "POST", "/v1.0/ip/security", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestGeocoderSearchWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.GeocoderSearchRequest{
		APIKey: "apiKey",
		Query:  "query",
	}
	_, invocationErr := client.GeocoderSearch(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestGeocoderSearchWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestGeocoderSearchWithWireMock", "GET", "/v1.0/geocoder/search", map[string]interface{}{"apiKey": "apiKey", "query": "query"}, 1)
}

func TestGeocoderReverseWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.GeocoderReverseRequest{
		APIKey: "apiKey",
		Lat:    1.1,
		Lon:    1.1,
	}
	_, invocationErr := client.GeocoderReverse(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestGeocoderReverseWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestGeocoderReverseWithWireMock", "GET", "/v1.0/geocoder/reverse", map[string]interface{}{"apiKey": "apiKey", "lat": "1.1", "lon": "1.1"}, 1)
}

func TestDomainWhoisLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.DomainWhoisLookupRequest{
		APIKey:     "apiKey",
		DomainName: "domainName",
	}
	_, invocationErr := client.DomainWhoisLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDomainWhoisLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDomainWhoisLookupWithWireMock", "GET", "/v1.0/domain/whois/live", map[string]interface{}{"apiKey": "apiKey", "domainName": "domainName"}, 1)
}

func TestBulkDomainWhoisLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.BulkDomainWhoisLookupRequest{
		APIKey: "apiKey",
		DomainNames: []string{
			"domainNames",
		},
	}
	_, invocationErr := client.BulkDomainWhoisLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBulkDomainWhoisLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBulkDomainWhoisLookupWithWireMock", "POST", "/v1.0/domain/whois/live", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestIPWhoisLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.IPWhoisLookupRequest{
		APIKey: "apiKey",
		IP:     "ip",
	}
	_, invocationErr := client.IPWhoisLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestIPWhoisLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestIPWhoisLookupWithWireMock", "GET", "/v1.0/ip/whois/live", map[string]interface{}{"apiKey": "apiKey", "ip": "ip"}, 1)
}

func TestAsnWhoisLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.AsnWhoisLookupRequest{
		APIKey: "apiKey",
		Asn:    "asn",
	}
	_, invocationErr := client.AsnWhoisLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAsnWhoisLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAsnWhoisLookupWithWireMock", "GET", "/v1.0/asn/whois/live", map[string]interface{}{"apiKey": "apiKey", "asn": "asn"}, 1)
}

func TestDomainWhoisHistoryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.DomainWhoisHistoryRequest{
		APIKey:     "apiKey",
		DomainName: "domainName",
	}
	_, invocationErr := client.DomainWhoisHistory(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDomainWhoisHistoryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDomainWhoisHistoryWithWireMock", "GET", "/v1.0/domain/whois/history", map[string]interface{}{"apiKey": "apiKey", "domainName": "domainName"}, 1)
}

func TestDomainWhoisReverseWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.DomainWhoisReverseRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.DomainWhoisReverse(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDomainWhoisReverseWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDomainWhoisReverseWithWireMock", "GET", "/v1.0/domain/whois/reverse", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestDomainDNSLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.DomainDNSLookupRequest{
		APIKey: "apiKey",
		Type: []*string{
			afgosdk.String(
				"type",
			),
		},
	}
	_, invocationErr := client.DomainDNSLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDomainDNSLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDomainDNSLookupWithWireMock", "GET", "/v1.0/domain/dns/live", map[string]interface{}{"apiKey": "apiKey", "type": "type"}, 1)
}

func TestBulkDomainDNSLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.BulkDomainDNSLookupRequest{
		APIKey: "apiKey",
		Type: []*string{
			afgosdk.String(
				"type",
			),
		},
		DomainNames: []string{
			"domainNames",
		},
	}
	_, invocationErr := client.BulkDomainDNSLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBulkDomainDNSLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBulkDomainDNSLookupWithWireMock", "POST", "/v1.0/domain/dns/live", map[string]interface{}{"apiKey": "apiKey", "type": "type"}, 1)
}

func TestDomainDNSHistoryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.DomainDNSHistoryRequest{
		APIKey:   "apiKey",
		HostName: "host-name",
		Type: []*string{
			afgosdk.String(
				"type",
			),
		},
	}
	_, invocationErr := client.DomainDNSHistory(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDomainDNSHistoryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDomainDNSHistoryWithWireMock", "GET", "/v1.0/domain/dns/history", map[string]interface{}{"apiKey": "apiKey", "host-name": "host-name", "type": "type"}, 1)
}

func TestDomainDNSReverseWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.DomainDNSReverseRequest{
		APIKey: "apiKey",
		Type:   afgosdk.DomainDNSReverseRequestTypeA,
		Value:  "value",
	}
	_, invocationErr := client.DomainDNSReverse(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDomainDNSReverseWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDomainDNSReverseWithWireMock", "GET", "/v1.0/domain/dns/reverse", map[string]interface{}{"apiKey": "apiKey", "type": "A", "value": "value"}, 1)
}

func TestWebScrapeWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.WebScrapeRequest{
		APIKey: "apiKey",
		URL:    "https://example.com",
		Body: &afgosdk.WebScrapeRequestBody{
			WebScrapeRequestBodyBlockURL: &afgosdk.WebScrapeRequestBodyBlockURL{
				BlockURL: []string{
					"https://example.com/ads.js",
					"https://tracker.example.com/*",
				},
				Cookies: []*afgosdk.WebScrapeRequestBodyBlockURLCookiesItem{
					&afgosdk.WebScrapeRequestBodyBlockURLCookiesItem{
						Name:  "sessionid",
						Value: "abc123",
					},
					&afgosdk.WebScrapeRequestBodyBlockURLCookiesItem{
						Name:  "user_pref",
						Value: "darkmode",
					},
				},
				Instructions: []*afgosdk.WebScrapeRequestBodyBlockURLInstructionsItem{
					&afgosdk.WebScrapeRequestBodyBlockURLInstructionsItem{
						WebScrapeRequestBodyBlockURLInstructionsItemFill: &afgosdk.WebScrapeRequestBodyBlockURLInstructionsItemFill{
							Fill: &afgosdk.WebScrapeRequestBodyBlockURLInstructionsItemFillFill{
								Place: "#username",
								Value: "myuser",
							},
						},
					},
					&afgosdk.WebScrapeRequestBodyBlockURLInstructionsItem{
						WebScrapeRequestBodyBlockURLInstructionsItemFill: &afgosdk.WebScrapeRequestBodyBlockURLInstructionsItemFill{
							Fill: &afgosdk.WebScrapeRequestBodyBlockURLInstructionsItemFillFill{
								Place: "#password",
								Value: "mypassword",
							},
						},
					},
					&afgosdk.WebScrapeRequestBodyBlockURLInstructionsItem{
						WebScrapeRequestBodyBlockURLInstructionsItemClick: &afgosdk.WebScrapeRequestBodyBlockURLInstructionsItemClick{
							Click: afgosdk.String(
								"#loginButton",
							),
						},
					},
					&afgosdk.WebScrapeRequestBodyBlockURLInstructionsItem{
						WebScrapeRequestBodyBlockURLInstructionsItemWait: &afgosdk.WebScrapeRequestBodyBlockURLInstructionsItemWait{
							Wait: afgosdk.Int(
								2000,
							),
						},
					},
					&afgosdk.WebScrapeRequestBodyBlockURLInstructionsItem{
						WebScrapeRequestBodyBlockURLInstructionsItemExtract: &afgosdk.WebScrapeRequestBodyBlockURLInstructionsItemExtract{
							Extract: &afgosdk.WebScrapeRequestBodyBlockURLInstructionsItemExtractExtract{
								HTML: afgosdk.String(
									"#profile",
								),
								Text: afgosdk.String(
									"#welcome-message",
								),
								UserData: afgosdk.String(
									"#user-info",
								),
							},
						},
					},
					&afgosdk.WebScrapeRequestBodyBlockURLInstructionsItem{
						WebScrapeRequestBodyBlockURLInstructionsItemBlockElement: &afgosdk.WebScrapeRequestBodyBlockURLInstructionsItemBlockElement{
							BlockElement: []string{
								".ad-banner",
								"//div[@class='popup']",
							},
						},
					},
					&afgosdk.WebScrapeRequestBodyBlockURLInstructionsItem{
						WebScrapeRequestBodyBlockURLInstructionsItemGeneralImageCaptcha: &afgosdk.WebScrapeRequestBodyBlockURLInstructionsItemGeneralImageCaptcha{
							GeneralImageCaptcha: []*afgosdk.WebScrapeRequestBodyBlockURLInstructionsItemGeneralImageCaptchaGeneralImageCaptchaItem{
								&afgosdk.WebScrapeRequestBodyBlockURLInstructionsItemGeneralImageCaptchaGeneralImageCaptchaItem{
									ImagePath: afgosdk.String(
										"#captcha-img",
									),
									TextField: afgosdk.String(
										"#captcha-input",
									),
									ImageUpdatePath: afgosdk.String(
										"#refresh-captcha",
									),
									CaptchaFailedPath: afgosdk.String(
										"#captcha-error",
									),
									Model: afgosdk.WebScrapeRequestBodyBlockURLInstructionsItemGeneralImageCaptchaGeneralImageCaptchaItemModelMiniOcrV1.Ptr(),
								},
							},
						},
					},
				},
			},
		},
	}
	_, invocationErr := client.WebScrape(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebScrapeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebScrapeWithWireMock", "POST", "/v1.0/scraping", map[string]interface{}{"apiKey": "apiKey", "url": "https://example.com"}, 1)
}

func TestEmailValidateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.EmailValidateRequest{
		APIKey: "apiKey",
		Email:  "email",
	}
	_, invocationErr := client.EmailValidate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEmailValidateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEmailValidateWithWireMock", "POST", "/v1.0/email-validation/single", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestBulkEmailValidateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.BulkEmailValidateRequest{
		APIKey: "apiKey",
		EmailData: []*afgosdk.BulkEmailValidateRequestEmailDataItem{
			&afgosdk.BulkEmailValidateRequestEmailDataItem{
				Email: "email",
			},
		},
	}
	_, invocationErr := client.BulkEmailValidate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBulkEmailValidateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBulkEmailValidateWithWireMock", "POST", "/v1.0/email-validation/bulk", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestPhoneValidateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PhoneValidateRequest{
		APIKey: "apiKey",
		Number: "+14155552671",
	}
	_, invocationErr := client.PhoneValidate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPhoneValidateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPhoneValidateWithWireMock", "POST", "/v1.0/phone/validation", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestBulkPhoneValidateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.BulkPhoneValidateRequest{
		APIKey: "apiKey",
		Numbers: []*afgosdk.BulkPhoneValidateRequestNumbersItem{
			&afgosdk.BulkPhoneValidateRequestNumbersItem{
				Number: "+14155552671",
			},
			&afgosdk.BulkPhoneValidateRequestNumbersItem{
				Number: "+447911123456",
			},
			&afgosdk.BulkPhoneValidateRequestNumbersItem{
				Number: "+919876543210",
			},
		},
	}
	_, invocationErr := client.BulkPhoneValidate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBulkPhoneValidateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBulkPhoneValidateWithWireMock", "POST", "/v1.0/phone/validation/bulk", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestDomainSslLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.DomainSslLookupRequest{
		APIKey:     "apiKey",
		DomainName: "domainName",
	}
	_, invocationErr := client.DomainSslLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDomainSslLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDomainSslLookupWithWireMock", "GET", "/v1.0/domain/ssl/live", map[string]interface{}{"apiKey": "apiKey", "domainName": "domainName"}, 1)
}

func TestDomainSslChainLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.DomainSslChainLookupRequest{
		APIKey:     "apiKey",
		DomainName: "domainName",
	}
	_, invocationErr := client.DomainSslChainLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDomainSslChainLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDomainSslChainLookupWithWireMock", "GET", "/v1.0/domain/ssl/live/chain", map[string]interface{}{"apiKey": "apiKey", "domainName": "domainName"}, 1)
}

func TestDomainAvailabilityCheckWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.DomainAvailabilityCheckRequest{
		APIKey: "apiKey",
		Domain: "domain",
	}
	_, invocationErr := client.DomainAvailabilityCheck(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDomainAvailabilityCheckWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDomainAvailabilityCheckWithWireMock", "GET", "/v1.0/domain/availability", map[string]interface{}{"apiKey": "apiKey", "domain": "domain"}, 1)
}

func TestBulkDomainAvailabilityCheckWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.BulkDomainAvailabilityCheckRequest{
		APIKey: "apiKey",
		DomainNames: []string{
			"domainNames",
		},
	}
	_, invocationErr := client.BulkDomainAvailabilityCheck(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBulkDomainAvailabilityCheckWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBulkDomainAvailabilityCheckWithWireMock", "POST", "/v1.0/domain/availability", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestDomainAvailabilitySuggestionsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.DomainAvailabilitySuggestionsRequest{
		APIKey: "apiKey",
		Domain: "domain",
	}
	_, invocationErr := client.DomainAvailabilitySuggestions(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestDomainAvailabilitySuggestionsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestDomainAvailabilitySuggestionsWithWireMock", "GET", "/v1.0/domain/availability/suggestions", map[string]interface{}{"apiKey": "apiKey", "domain": "domain"}, 1)
}

func TestSubdomainsLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.SubdomainsLookupRequest{
		APIKey: "apiKey",
		Domain: "domain",
	}
	_, invocationErr := client.SubdomainsLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSubdomainsLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSubdomainsLookupWithWireMock", "GET", "/v1.0/subdomains/lookup", map[string]interface{}{"apiKey": "apiKey", "domain": "domain"}, 1)
}

func TestPdfMergeWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfMergeRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.PdfMerge(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfMergeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfMergeWithWireMock", "POST", "/v1.0/pdf/merge", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestPdfRemovePagesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfRemovePagesRequest{
		APIKey: "apiKey",
		Pages:  "pages",
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.PdfRemovePages(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfRemovePagesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfRemovePagesWithWireMock", "POST", "/v1.0/pdf/remove-pages", map[string]interface{}{"apiKey": "apiKey", "pages": "pages"}, 1)
}

func TestPdfSplitWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfSplitRequest{
		APIKey: "apiKey",
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.PdfSplit(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfSplitWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfSplitWithWireMock", "POST", "/v1.0/pdf/split", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestPdfRotateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfRotateRequest{
		APIKey: "apiKey",
		Rotate: 1,
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.PdfRotate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfRotateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfRotateWithWireMock", "POST", "/v1.0/pdf/rotate", map[string]interface{}{"apiKey": "apiKey", "rotate": "1"}, 1)
}

func TestPdfCompressWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfCompressRequest{
		APIKey:           "apiKey",
		CompressionLevel: afgosdk.PdfCompressRequestCompressionLevelLow,
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.PdfCompress(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfCompressWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfCompressWithWireMock", "POST", "/v1.0/pdf/compress", map[string]interface{}{"apiKey": "apiKey", "compression_level": "low"}, 1)
}

func TestPdfExtractPagesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfExtractPagesRequest{
		APIKey: "apiKey",
		Pages:  "pages",
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.PdfExtractPages(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfExtractPagesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfExtractPagesWithWireMock", "POST", "/v1.0/pdf/extract-pages", map[string]interface{}{"apiKey": "apiKey", "pages": "pages"}, 1)
}

func TestPdfLinearizeWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfLinearizeRequest{
		APIKey: "apiKey",
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.PdfLinearize(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfLinearizeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfLinearizeWithWireMock", "POST", "/v1.0/pdf/linearize", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestPdfEncryptWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfEncryptRequest{
		APIKey:       "apiKey",
		UserPassword: "user_password",
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.PdfEncrypt(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfEncryptWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfEncryptWithWireMock", "POST", "/v1.0/pdf/encrypt", map[string]interface{}{"apiKey": "apiKey", "user_password": "user_password"}, 1)
}

func TestPdfDecryptWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfDecryptRequest{
		APIKey:       "apiKey",
		FilePassword: "file_password",
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.PdfDecrypt(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfDecryptWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfDecryptWithWireMock", "POST", "/v1.0/pdf/decrypt", map[string]interface{}{"apiKey": "apiKey", "file_password": "file_password"}, 1)
}

func TestPdfRestrictWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfRestrictRequest{
		APIKey:       "apiKey",
		UserPassword: "user_password",
		Restrictions: []*afgosdk.PdfRestrictRequestRestrictionsItem{
			afgosdk.PdfRestrictRequestRestrictionsItemPrintHigh.Ptr(),
		},
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.PdfRestrict(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfRestrictWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfRestrictWithWireMock", "POST", "/v1.0/pdf/restrict", map[string]interface{}{"apiKey": "apiKey", "user_password": "user_password", "restrictions": "print_high"}, 1)
}

func TestPdfUnrestrictWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfUnrestrictRequest{
		APIKey:       "apiKey",
		FilePassword: "file_password",
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.PdfUnrestrict(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfUnrestrictWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfUnrestrictWithWireMock", "POST", "/v1.0/pdf/unrestrict", map[string]interface{}{"apiKey": "apiKey", "file_password": "file_password"}, 1)
}

func TestPdfConvertToPngWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfConvertToPngRequest{
		APIKey: "apiKey",
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.PdfConvertToPng(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfConvertToPngWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfConvertToPngWithWireMock", "POST", "/v1.0/pdf/png", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestPdfConvertToJpgWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfConvertToJpgRequest{
		APIKey: "apiKey",
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.PdfConvertToJpg(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfConvertToJpgWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfConvertToJpgWithWireMock", "POST", "/v1.0/pdf/jpg", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestPdfConvertToTiffWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfConvertToTiffRequest{
		APIKey: "apiKey",
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.PdfConvertToTiff(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfConvertToTiffWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfConvertToTiffWithWireMock", "POST", "/v1.0/pdf/tif", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestPdfConvertToBmpWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfConvertToBmpRequest{
		APIKey: "apiKey",
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.PdfConvertToBmp(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfConvertToBmpWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfConvertToBmpWithWireMock", "POST", "/v1.0/pdf/bmp", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestPdfConvertToGifWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfConvertToGifRequest{
		APIKey: "apiKey",
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.PdfConvertToGif(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfConvertToGifWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfConvertToGifWithWireMock", "POST", "/v1.0/pdf/gif", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestPdfUploadResourcesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfUploadResourcesRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.PdfUploadResources(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfUploadResourcesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfUploadResourcesWithWireMock", "POST", "/v1.0/pdf/resource/upload", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestPdfDownloadResourceWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfDownloadResourceRequest{
		APIKey:     "apiKey",
		ResourceID: "resource_id",
	}
	_, invocationErr := client.PdfDownloadResource(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfDownloadResourceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfDownloadResourceWithWireMock", "GET", "/v1.0/pdf/resource/download", map[string]interface{}{"apiKey": "apiKey", "resource_id": "resource_id"}, 1)
}

func TestPdfGetTaskStatusWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfGetTaskStatusRequest{
		APIKey: "apiKey",
		TaskID: "task_id",
	}
	_, invocationErr := client.PdfGetTaskStatus(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfGetTaskStatusWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfGetTaskStatusWithWireMock", "GET", "/v1.0/pdf/task-status", map[string]interface{}{"apiKey": "apiKey", "task_id": "task_id"}, 1)
}

func TestPdfGetFileStatusWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfGetFileStatusRequest{
		APIKey: "apiKey",
		FileID: "file_id",
	}
	_, invocationErr := client.PdfGetFileStatus(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfGetFileStatusWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfGetFileStatusWithWireMock", "GET", "/v1.0/pdf/file-status", map[string]interface{}{"apiKey": "apiKey", "file_id": "file_id"}, 1)
}

func TestPdfListFilesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfListFilesRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.PdfListFiles(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfListFilesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfListFilesWithWireMock", "GET", "/v1.0/pdf/files", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestPdfDeleteFileWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.PdfDeleteFileRequest{
		APIKey: "apiKey",
		FileID: "file_id",
	}
	_, invocationErr := client.PdfDeleteFile(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPdfDeleteFileWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPdfDeleteFileWithWireMock", "DELETE", "/v1.0/pdf/file", map[string]interface{}{"apiKey": "apiKey", "file_id": "file_id"}, 1)
}

func TestScreenshotCaptureWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.ScreenshotCaptureRequest{
		APIKey: "apiKey",
		URL:    "url",
	}
	_, invocationErr := client.ScreenshotCapture(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestScreenshotCaptureWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestScreenshotCaptureWithWireMock", "GET", "/v1.0/screenshot", map[string]interface{}{"apiKey": "apiKey", "url": "url"}, 1)
}

func TestBulkScreenshotCaptureWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.BulkScreenshotCaptureRequest{
		APIKey: "apiKey",
		URLs: []*afgosdk.BulkScreenshotCaptureRequestURLsItem{
			&afgosdk.BulkScreenshotCaptureRequestURLsItem{
				URL: "url",
			},
		},
	}
	_, invocationErr := client.BulkScreenshotCapture(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBulkScreenshotCaptureWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBulkScreenshotCaptureWithWireMock", "POST", "/v1.0/screenshot", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestCurrencyLatestRatesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.CurrencyLatestRatesRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.CurrencyLatestRates(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCurrencyLatestRatesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCurrencyLatestRatesWithWireMock", "GET", "/v1.0/currency/rates/latest", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestCurrencyHistoricalRatesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.CurrencyHistoricalRatesRequest{
		APIKey: "apiKey",
		Date: afgosdk.MustParseDate(
			"2023-01-15",
		),
	}
	_, invocationErr := client.CurrencyHistoricalRates(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCurrencyHistoricalRatesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCurrencyHistoricalRatesWithWireMock", "GET", "/v1.0/currency/rates/historical", map[string]interface{}{"apiKey": "apiKey", "date": "2023-01-15"}, 1)
}

func TestCurrencyConvertLatestWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.CurrencyConvertLatestRequest{
		APIKey: "apiKey",
		From:   "from",
		To:     "to",
	}
	_, invocationErr := client.CurrencyConvertLatest(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCurrencyConvertLatestWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCurrencyConvertLatestWithWireMock", "GET", "/v1.0/currency/converter/latest/prices", map[string]interface{}{"apiKey": "apiKey", "from": "from", "to": "to"}, 1)
}

func TestCurrencyConvertHistoricalWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.CurrencyConvertHistoricalRequest{
		APIKey: "apiKey",
		From:   "from",
		To:     "to",
		Date: afgosdk.MustParseDate(
			"2023-01-15",
		),
	}
	_, invocationErr := client.CurrencyConvertHistorical(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCurrencyConvertHistoricalWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCurrencyConvertHistoricalWithWireMock", "GET", "/v1.0/currency/converter/historical/prices", map[string]interface{}{"apiKey": "apiKey", "from": "from", "to": "to", "date": "2023-01-15"}, 1)
}

func TestCurrencyTimeSeriesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.CurrencyTimeSeriesRequest{
		APIKey: "apiKey",
		StartDate: afgosdk.MustParseDate(
			"2023-01-15",
		),
	}
	_, invocationErr := client.CurrencyTimeSeries(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCurrencyTimeSeriesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCurrencyTimeSeriesWithWireMock", "GET", "/v1.0/currency/time-series", map[string]interface{}{"apiKey": "apiKey", "startDate": "2023-01-15"}, 1)
}

func TestCurrencyFluctuationWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.CurrencyFluctuationRequest{
		APIKey: "apiKey",
		StartDate: afgosdk.MustParseDate(
			"2023-01-15",
		),
		Base: afgosdk.String(
			"USD",
		),
	}
	_, invocationErr := client.CurrencyFluctuation(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCurrencyFluctuationWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCurrencyFluctuationWithWireMock", "GET", "/v1.0/currency/fluctuation", map[string]interface{}{"apiKey": "apiKey", "startDate": "2023-01-15", "base": "USD"}, 1)
}

func TestCurrencyConvertByIPWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.CurrencyConvertByIPRequest{
		APIKey: "apiKey",
		From:   "from",
	}
	_, invocationErr := client.CurrencyConvertByIP(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCurrencyConvertByIPWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCurrencyConvertByIPWithWireMock", "GET", "/v1.0/currency/converter/ip-to-currency", map[string]interface{}{"apiKey": "apiKey", "from": "from"}, 1)
}

func TestCurrencySupportedWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.CurrencySupportedRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.CurrencySupported(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCurrencySupportedWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCurrencySupportedWithWireMock", "GET", "/v1.0/currency/supported", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestCurrencySymbolsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.CurrencySymbolsRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.CurrencySymbols(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCurrencySymbolsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCurrencySymbolsWithWireMock", "GET", "/v1.0/currency/symbols", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestCurrencyHistoricalLimitsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.CurrencyHistoricalLimitsRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.CurrencyHistoricalLimits(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCurrencyHistoricalLimitsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCurrencyHistoricalLimitsWithWireMock", "GET", "/v1.0/currency/historical/data/limits", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestCommodityLatestRatesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.CommodityLatestRatesRequest{
		APIKey: "apiKey",
		Symbols: []*string{
			afgosdk.String(
				"symbols",
			),
		},
		Updates: afgosdk.CommodityLatestRatesRequestUpdatesTenM,
	}
	_, invocationErr := client.CommodityLatestRates(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCommodityLatestRatesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCommodityLatestRatesWithWireMock", "GET", "/v1.0/commodity/rates/latest", map[string]interface{}{"apiKey": "apiKey", "symbols": "symbols", "updates": "10m"}, 1)
}

func TestCommodityHistoricalRatesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.CommodityHistoricalRatesRequest{
		APIKey: "apiKey",
		Date: afgosdk.MustParseDate(
			"2023-01-15",
		),
		Symbols: []*string{
			afgosdk.String(
				"symbols",
			),
		},
	}
	_, invocationErr := client.CommodityHistoricalRates(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCommodityHistoricalRatesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCommodityHistoricalRatesWithWireMock", "GET", "/v1.0/commodity/rates/historical", map[string]interface{}{"apiKey": "apiKey", "date": "2023-01-15", "symbols": "symbols"}, 1)
}

func TestCommodityFluctuationWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.CommodityFluctuationRequest{
		APIKey: "apiKey",
		Symbols: []*string{
			afgosdk.String(
				"symbols",
			),
		},
		StartDate: afgosdk.MustParseDate(
			"2023-01-15",
		),
		EndDate: afgosdk.MustParseDate(
			"2023-01-15",
		),
	}
	_, invocationErr := client.CommodityFluctuation(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCommodityFluctuationWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCommodityFluctuationWithWireMock", "GET", "/v1.0/commodity/fluctuation", map[string]interface{}{"apiKey": "apiKey", "symbols": "symbols", "startDate": "2023-01-15", "endDate": "2023-01-15"}, 1)
}

func TestCommodityTimeSeriesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.CommodityTimeSeriesRequest{
		APIKey: "apiKey",
		Symbols: []*string{
			afgosdk.String(
				"symbols",
			),
		},
		StartDate: afgosdk.MustParseDate(
			"2023-01-15",
		),
		EndDate: afgosdk.MustParseDate(
			"2023-01-15",
		),
	}
	_, invocationErr := client.CommodityTimeSeries(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCommodityTimeSeriesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCommodityTimeSeriesWithWireMock", "GET", "/v1.0/commodity/time-series", map[string]interface{}{"apiKey": "apiKey", "symbols": "symbols", "startDate": "2023-01-15", "endDate": "2023-01-15"}, 1)
}

func TestCommoditySymbolsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.CommoditySymbolsRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.CommoditySymbols(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCommoditySymbolsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCommoditySymbolsWithWireMock", "GET", "/v1.0/commodity/symbols", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestVatSupportedCountriesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.VatSupportedCountriesRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.VatSupportedCountries(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestVatSupportedCountriesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestVatSupportedCountriesWithWireMock", "GET", "/v1.0/vat/supported-countries", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestVatRateByIPWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.VatRateByIPRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.VatRateByIP(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestVatRateByIPWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestVatRateByIPWithWireMock", "GET", "/v1.0/vat/rates/ip-address", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestVatRateByCountryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.VatRateByCountryRequest{
		APIKey:  "apiKey",
		Country: "country",
	}
	_, invocationErr := client.VatRateByCountry(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestVatRateByCountryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestVatRateByCountryWithWireMock", "GET", "/v1.0/vat/rates/country", map[string]interface{}{"apiKey": "apiKey", "country": "country"}, 1)
}

func TestBulkVatRateByCountryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.BulkVatRateByCountryRequest{
		APIKey: "apiKey",
		Countries: []*afgosdk.BulkVatRateByCountryRequestCountriesItem{
			&afgosdk.BulkVatRateByCountryRequestCountriesItem{
				Country: "PAK",
			},
			&afgosdk.BulkVatRateByCountryRequestCountriesItem{
				Country: "United_States",
				State: afgosdk.String(
					"New_York",
				),
			},
		},
	}
	_, invocationErr := client.BulkVatRateByCountry(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBulkVatRateByCountryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBulkVatRateByCountryWithWireMock", "POST", "/v1.0/vat/rates/country", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestVatValidateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.VatValidateRequest{
		APIKey:    "apiKey",
		VatNumber: "vatNumber",
	}
	_, invocationErr := client.VatValidate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestVatValidateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestVatValidateWithWireMock", "GET", "/v1.0/vat/validation", map[string]interface{}{"apiKey": "apiKey", "vatNumber": "vatNumber"}, 1)
}

func TestIbanValidateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.IbanValidateRequest{
		APIKey: "apiKey",
		Iban:   "iban",
	}
	_, invocationErr := client.IbanValidate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestIbanValidateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestIbanValidateWithWireMock", "GET", "/v1.0/iban/validation", map[string]interface{}{"apiKey": "apiKey", "iban": "iban"}, 1)
}

func TestSwiftCodeFindWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.SwiftCodeFindRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.SwiftCodeFind(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSwiftCodeFindWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSwiftCodeFindWithWireMock", "GET", "/v1.0/swift-code/finder", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestSwiftCodeLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.SwiftCodeLookupRequest{
		APIKey:    "apiKey",
		SwiftCode: "swiftCode",
	}
	_, invocationErr := client.SwiftCodeLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSwiftCodeLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSwiftCodeLookupWithWireMock", "GET", "/v1.0/swift-code/lookup", map[string]interface{}{"apiKey": "apiKey", "swiftCode": "swiftCode"}, 1)
}

func TestZipcodeLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.ZipcodeLookupRequest{
		APIKey: "apiKey",
		Code:   "code",
	}
	_, invocationErr := client.ZipcodeLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestZipcodeLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestZipcodeLookupWithWireMock", "GET", "/v1.0/zipcode/lookup", map[string]interface{}{"apiKey": "apiKey", "code": "code"}, 1)
}

func TestBulkZipcodeLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.BulkZipcodeLookupRequest{
		APIKey: "apiKey",
		Codes: []string{
			"codes",
		},
	}
	_, invocationErr := client.BulkZipcodeLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBulkZipcodeLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBulkZipcodeLookupWithWireMock", "POST", "/v1.0/zipcode/lookup", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestZipcodeSearchByCityWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.ZipcodeSearchByCityRequest{
		APIKey:  "apiKey",
		City:    "city",
		Country: "country",
	}
	_, invocationErr := client.ZipcodeSearchByCity(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestZipcodeSearchByCityWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestZipcodeSearchByCityWithWireMock", "GET", "/v1.0/zipcode/search/city", map[string]interface{}{"apiKey": "apiKey", "city": "city", "country": "country"}, 1)
}

func TestZipcodeSearchByRegionWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.ZipcodeSearchByRegionRequest{
		APIKey:  "apiKey",
		Country: "country",
		Region:  "region",
	}
	_, invocationErr := client.ZipcodeSearchByRegion(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestZipcodeSearchByRegionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestZipcodeSearchByRegionWithWireMock", "GET", "/v1.0/zipcode/search/region", map[string]interface{}{"apiKey": "apiKey", "country": "country", "region": "region"}, 1)
}

func TestZipcodeSearchByRadiusWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.ZipcodeSearchByRadiusRequest{
		APIKey: "apiKey",
		Radius: 1.1,
	}
	_, invocationErr := client.ZipcodeSearchByRadius(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestZipcodeSearchByRadiusWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestZipcodeSearchByRadiusWithWireMock", "GET", "/v1.0/zipcode/search/radius", map[string]interface{}{"apiKey": "apiKey", "radius": "1.1"}, 1)
}

func TestZipcodeDistanceWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.ZipcodeDistanceRequest{
		APIKey: "apiKey",
		Compare: []string{
			"compare",
		},
		Country: "country",
	}
	_, invocationErr := client.ZipcodeDistance(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestZipcodeDistanceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestZipcodeDistanceWithWireMock", "POST", "/v1.0/zipcode/distance", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestZipcodeDistanceMatchWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.ZipcodeDistanceMatchRequest{
		APIKey: "apiKey",
		Codes: []string{
			"codes",
		},
		Country: "country",
	}
	_, invocationErr := client.ZipcodeDistanceMatch(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestZipcodeDistanceMatchWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestZipcodeDistanceMatchWithWireMock", "POST", "/v1.0/zipcode/distance/match", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestCurrentWeatherWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.CurrentWeatherRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.CurrentWeather(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestCurrentWeatherWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestCurrentWeatherWithWireMock", "GET", "/v1.0/weather/current", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestBulkCurrentWeatherWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.BulkCurrentWeatherRequest{
		APIKey: "apiKey",
		Locations: []*afgosdk.BulkCurrentWeatherRequestLocationsItem{
			&afgosdk.BulkCurrentWeatherRequestLocationsItem{
				Location: afgosdk.String(
					"lahore",
				),
			},
			&afgosdk.BulkCurrentWeatherRequestLocationsItem{
				Lat: afgosdk.Float64(
					32.5,
				),
				Long: afgosdk.Float64(
					74.5,
				),
			},
			&afgosdk.BulkCurrentWeatherRequestLocationsItem{
				IP: afgosdk.String(
					"8.8.8.8",
				),
			},
			&afgosdk.BulkCurrentWeatherRequestLocationsItem{
				Location: afgosdk.String(
					"seoul",
				),
			},
		},
	}
	_, invocationErr := client.BulkCurrentWeather(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBulkCurrentWeatherWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBulkCurrentWeatherWithWireMock", "POST", "/v1.0/weather/current", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestWeatherForecastWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.WeatherForecastRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.WeatherForecast(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWeatherForecastWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWeatherForecastWithWireMock", "GET", "/v1.0/weather/forecast", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestHistoricalWeatherWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.HistoricalWeatherRequest{
		APIKey: "apiKey",
		Date: afgosdk.MustParseDate(
			"2023-01-15",
		),
	}
	_, invocationErr := client.HistoricalWeather(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestHistoricalWeatherWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestHistoricalWeatherWithWireMock", "GET", "/v1.0/weather/historical", map[string]interface{}{"apiKey": "apiKey", "date": "2023-01-15"}, 1)
}

func TestWeatherTimeSeriesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.WeatherTimeSeriesRequest{
		APIKey: "apiKey",
		StartDate: afgosdk.MustParseDate(
			"2023-01-15",
		),
		EndDate: afgosdk.MustParseDate(
			"2023-01-15",
		),
	}
	_, invocationErr := client.WeatherTimeSeries(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWeatherTimeSeriesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWeatherTimeSeriesWithWireMock", "GET", "/v1.0/weather/time-series", map[string]interface{}{"apiKey": "apiKey", "startDate": "2023-01-15", "endDate": "2023-01-15"}, 1)
}

func TestMarineWeatherWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.MarineWeatherRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.MarineWeather(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMarineWeatherWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMarineWeatherWithWireMock", "GET", "/v1.0/weather/marine", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestAirQualityWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.AirQualityRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.AirQuality(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAirQualityWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAirQualityWithWireMock", "GET", "/v1.0/weather/air-quality", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestFloodForecastWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.FloodForecastRequest{
		APIKey: "apiKey",
		StartDate: afgosdk.MustParseDate(
			"2023-01-15",
		),
		EndDate: afgosdk.MustParseDate(
			"2023-01-15",
		),
	}
	_, invocationErr := client.FloodForecast(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFloodForecastWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFloodForecastWithWireMock", "GET", "/v1.0/weather/flood", map[string]interface{}{"apiKey": "apiKey", "startDate": "2023-01-15", "endDate": "2023-01-15"}, 1)
}

func TestGetCountriesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.GetCountriesRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.GetCountries(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestGetCountriesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestGetCountriesWithWireMock", "GET", "/v1.0/geo/countries", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestGetCountryDetailsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.GetCountryDetailsRequest{
		APIKey:  "apiKey",
		Country: "country",
	}
	_, invocationErr := client.GetCountryDetails(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestGetCountryDetailsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestGetCountryDetailsWithWireMock", "GET", "/v1.0/geo/country/details", map[string]interface{}{"apiKey": "apiKey", "country": "country"}, 1)
}

func TestGetRegionsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.GetRegionsRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.GetRegions(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestGetRegionsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestGetRegionsWithWireMock", "GET", "/v1.0/geo/regions", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestGetSubregionsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.GetSubregionsRequest{
		APIKey: "apiKey",
		Region: "region",
	}
	_, invocationErr := client.GetSubregions(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestGetSubregionsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestGetSubregionsWithWireMock", "GET", "/v1.0/geo/subregions", map[string]interface{}{"apiKey": "apiKey", "region": "region"}, 1)
}

func TestGetAdminLevelsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.GetAdminLevelsRequest{
		APIKey:  "apiKey",
		Country: "country",
	}
	_, invocationErr := client.GetAdminLevels(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestGetAdminLevelsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestGetAdminLevelsWithWireMock", "GET", "/v1.0/geo/admin-levels", map[string]interface{}{"apiKey": "apiKey", "country": "country"}, 1)
}

func TestGetAdminUnitsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.GetAdminUnitsRequest{
		APIKey:  "apiKey",
		Country: "country",
	}
	_, invocationErr := client.GetAdminUnits(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestGetAdminUnitsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestGetAdminUnitsWithWireMock", "GET", "/v1.0/geo/admin-units", map[string]interface{}{"apiKey": "apiKey", "country": "country"}, 1)
}

func TestGetAdminUnitDetailsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.GetAdminUnitDetailsRequest{
		APIKey:    "apiKey",
		Country:   "country",
		AdminUnit: "admin_unit",
	}
	_, invocationErr := client.GetAdminUnitDetails(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestGetAdminUnitDetailsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestGetAdminUnitDetailsWithWireMock", "GET", "/v1.0/geo/admin-unit/details", map[string]interface{}{"apiKey": "apiKey", "country": "country", "admin_unit": "admin_unit"}, 1)
}

func TestGetCitiesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.GetCitiesRequest{
		APIKey:  "apiKey",
		Country: "country",
	}
	_, invocationErr := client.GetCities(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestGetCitiesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestGetCitiesWithWireMock", "GET", "/v1.0/geo/cities", map[string]interface{}{"apiKey": "apiKey", "country": "country"}, 1)
}

func TestGetSupportedFlagsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.GetSupportedFlagsRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.GetSupportedFlags(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestGetSupportedFlagsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestGetSupportedFlagsWithWireMock", "GET", "/v1.0/flags/supported", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestGetFlagsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.GetFlagsRequest{
		APIKey: "apiKey",
		Name:   "name",
		Shape:  afgosdk.GetFlagsRequestShapeFlat,
		Type:   afgosdk.GetFlagsRequestTypeCountry,
	}
	_, invocationErr := client.GetFlags(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestGetFlagsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestGetFlagsWithWireMock", "GET", "/v1.0/flags", map[string]interface{}{"apiKey": "apiKey", "name": "name", "shape": "flat", "type": "country"}, 1)
}

func TestTimezoneLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.TimezoneLookupRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.TimezoneLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTimezoneLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTimezoneLookupWithWireMock", "GET", "/v1.0/geolocation/timezone", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestTimezoneConvertWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.TimezoneConvertRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.TimezoneConvert(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTimezoneConvertWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTimezoneConvertWithWireMock", "GET", "/v1.0/timezone/converter", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestUserAgentLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.UserAgentLookupRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.UserAgentLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestUserAgentLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestUserAgentLookupWithWireMock", "GET", "/v1.0/user-agent/lookup", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestBulkUserAgentLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.BulkUserAgentLookupRequest{
		APIKey: "apiKey",
		UaStrings: []string{
			"uaStrings",
		},
	}
	_, invocationErr := client.BulkUserAgentLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBulkUserAgentLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBulkUserAgentLookupWithWireMock", "POST", "/v1.0/user-agent/lookup", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestOcrPredictWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.OcrPredictRequest{
		APIKey:                 "apiKey",
		Model:                  afgosdk.OcrPredictRequestModelMiniOcrV1,
		OcrPredictRequestModel: afgosdk.OcrPredictRequestModelMiniOcrV1,
	}
	_, invocationErr := client.OcrPredict(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOcrPredictWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOcrPredictWithWireMock", "POST", "/v1.0/ocr/predict", map[string]interface{}{"apiKey": "apiKey", "model": "mini-ocr-v1"}, 1)
}

func TestGrammarDetectWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.GrammarDetectRequest{
		APIKey: "apiKey",
		Text:   "The global mental is health crisis is now a serious and compelex problem. It need quick and ongoing action from policymakers, healthcare workers, and the whole society.",
	}
	_, invocationErr := client.GrammarDetect(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestGrammarDetectWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestGrammarDetectWithWireMock", "POST", "/v1.0/readability/grammar/detect", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestGrammarCorrectWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.GrammarCorrectRequest{
		APIKey: "apiKey",
		Text:   "The global mental is health crisis is now a serious and compelex problem. It need quick and ongoing action from policymakers, healthcare workers, and the whole society.",
	}
	_, invocationErr := client.GrammarCorrect(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestGrammarCorrectWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestGrammarCorrectWithWireMock", "POST", "/v1.0/readability/grammar/correct", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestWeakWordsDetectWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.WeakWordsDetectRequest{
		APIKey: "apiKey",
		Text:   "Many people cannot get the support they need to handle their conditions well.",
	}
	_, invocationErr := client.WeakWordsDetect(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWeakWordsDetectWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWeakWordsDetectWithWireMock", "POST", "/v1.0/readability/weak-words", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestReadabilityScoreWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.ReadabilityScoreRequest{
		APIKey: "apiKey",
		Text:   "The global mental is health crisis is now a serious and compelex problem. It needs quick and ongoing action from policymakers, healthcare workers, and the whole society.",
	}
	_, invocationErr := client.ReadabilityScore(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReadabilityScoreWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReadabilityScoreWithWireMock", "POST", "/v1.0/readability/score", map[string]interface{}{"apiKey": "apiKey"}, 1)
}

func TestAstronomyLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &afgosdk.AstronomyLookupRequest{
		APIKey: "apiKey",
	}
	_, invocationErr := client.AstronomyLookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAstronomyLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAstronomyLookupWithWireMock", "GET", "/v1.0/geolocation/astronomy", map[string]interface{}{"apiKey": "apiKey"}, 1)
}
